### ISSUE TITLE
Медленное выполнение команды

### ISSUE THREAD

**Issue by ildary** [arkuznetsov/irac#32]
Скажите пожалуйста, отчего может происходить медленное выполнение команды: 

Кластер_Агент.ВыполнитьКоманду(ПараметрыЗапуска);

Параметры выполнения: "infobase" и "info" - получаем данные по базе (в моём случае флаг блокировки).

OneScript выполненяется на том же компьютере, что и сервер 1С и его сервер администрирования. Всё остальное не тормозит. 1С 8.3.10.2699, Windows server 2008 R2 Standart SP1.

**Comment by arkuznetsov** [comment]
А пробовали выполнить команду infobase info непосредственно из командной строки? Быстрее выполняется?

**Comment by arkuznetsov** [comment]
Врятли проблема в настройках 1С, т.к. при использовании консоли администрирования 1С, также есть существенная задержка при первом открытии полной информации об ИБ. Видимо проблема где-то глубже.
Есть еще костыльный вариант, читать информацию об ИБ напрямую из файлов настройки кластера, но там еще доп. костыли по получению этих файлов в случае сложной конфигурации кластера.
Если еще альтернативные консоли на java-API, например: https://github.com/alekseybochkov/WebRAS/, не проверял, но вроде там тоже взаимодействие с RAS используется.

**Comment by ildary** [comment]
Спасибо за подробный ответ. Если тормозит сама 1С - будем терпеть.

**Comment by arkuznetsov** [comment]
Но это все не отменяет, того, что со временем irac будет оптимизироваться.
