### ISSUE TITLE
Непредвиденное поведение

### ISSUE THREAD

**Issue by SaintMortum** [arkuznetsov/irac#36]
Если попытаться заблокировать базу таким образом, то некоторые остальные свойства базы заполняет значениями по умолчанию. Например, сервер баз данных меняется на "localhost".

ДанныеЗаполнения = Новый Структура;
ДанныеЗаполнения.Вставить("НачалоБлокировкиСеансов", "2018-12-30T16:40:00");
ДанныеЗаполнения.Вставить("БлокировкаСеансовВключена", Истина);
База1с.Изменить(ДанныеЗаполнения);

Можно ли менять определённые свойства базы не указывая все свойства или так задумано?

**Comment by arkuznetsov** [comment]
Такого быть не должно, спасибо, посмотрю.
