### ISSUE TITLE
rac.exe запускается (открывается консоль), но ничего более не происходит 

### ISSUE THREAD

**Issue by Lopner** [arkuznetsov/irac#37]
Знакомлюсь с данной библиотекой, создал пример:

#Использовать irac

Админка = Новый АдминистрированиеКластера("localhost", 1545, "8.3");
Кластеры = Админка.Кластеры();
// Обходим список кластеров
Для Каждого Кластер Из Кластеры.Список() Цикл
    Сообщить(Кластер.Получить("Имя"));
КонецЦикла;

Порт, название, версию указал. Но получить список кластеров никак не получается. Сервак развернут локально на компе. Rac.exe открывается, но тупо висит и ничего не происходит

**Comment by arkuznetsov** [comment]
@Lopner А сервис RAS поднят?

**Comment by Lopner** [comment]
Разобрался, действительно не поднят был сервис ras, и с портами напутал. 

Попытался получить список сеансов, 30 минут появлялось и закрывалось консольное окошко rac.exe, и получил инфу о 300 сеансах. Реализован ли какой то более быстрый механизм?

И немогу найти как можно установить блокировку начала сеансов для конкретной бд
