### ISSUE TITLE
Вылезает иногда такое Предупрежедние

### ISSUE THREAD

**Issue by Lopner** [arkuznetsov/irac#40]
ПРЕДУПРЕЖДЕНИЕ - Не удалось прочитать версию 1С "C:\Program Files (x86)\1cv8\8.3.12.1790\bin\rac.exe" -v .
{Модуль C:\Program Files (x86)\OneScript\lib\asserts\src\bdd-asserts.os / Ошибка в строке: 336 / [Failed] Ожидали, что проверяемое значение (-1073741819) БОЛЬШЕ ИЛИ РАВНО (0).
Ожидали, что код возврата <-1073741819> команды <"C:\Program Files (x86)\1cv8\8.3.12.1790\bin\rac.exe" -v > совпадет с ожидаемым <0>, а это не так!
Лог команды:
8.3.12.1790
, вывод 8.3.12.1790
Стек трейс:
  C:\Program Files (x86)\OneScript\lib\asserts\src\bdd-asserts.os / Метод БольшеИлиРавно / Строка 89
    C:\Program Files (x86)\OneScript\lib\1commands\src\Команда.os / Метод ПроверитьКодВозврата / Строка 466
      C:\Program Files (x86)\OneScript\lib\1commands\src\Команда.os / Метод ЗапуститьИПодождать / Строка 346
        C:\Program Files (x86)\OneScript\lib\1commands\src\Команда.os / Метод Исполнить / Строка 34
          C:\Program Files (x86)\OneScript\lib\irac\src\Классы\ИсполнительКоманд.os / Метод ПолучитьВерсиюУтилитыАдминистрирования / Строка 410
            C:\Program Files (x86)\OneScript\lib\irac\src\Классы\ИсполнительКоманд.os / Метод ИнициализироватьУтилитуАдминистрирования / Строка 54
              C:\Program Files (x86)\OneScript\lib\irac\src\Классы\ИсполнительКоманд.os / Метод ПриСозданииОбъекта / Строка 22
                C:\Program Files (x86)\OneScript\lib\irac\src\Классы\АдминистрированиеКластера.os / Метод ПриСозданииОбъекта / Строка 31
                  C:\GIT_repozitories\git_1cAdminScripts\Кластреы моего локального сервера.os / Метод получитьДанныеСервреа / Строка 36
                    C:\GIT_repozitories\git_1cAdminScripts\Кластреы моего локального сервера.os / Метод $entry / Строка 80}

**Comment by arkuznetsov** [comment]
Утилита rac отработала некорректно и вернула код ошибки.
