### ISSUE TITLE
Добавление базы в кластер

### ISSUE THREAD

**Issue by leandr92** [arkuznetsov/irac#42]
Есть вопрос. У метода Добавить класса ИнформационныеБазы есть параметр "СоздатьБазуСУБД", влияет ли этот параметр хоть на что-то? в макетах я не нашел определения поведения для этого параметра команды, и результирующая строка формируется без параметра "--create-database". Может я что-то делаю неправильно?

```
ИБ = Кластер.ИнформационныеБазы();

ПараметрыБазы = Новый Структура();

ПараметрыБазы.Вставить("АдресСервераСУБД", "localhost");
ПараметрыБазы.Вставить("ТипСУБД", "PostgreSQL");
ПараметрыБазы.Вставить("ИмяБазыСУБД", ИмяНовойБазы);
ПараметрыБазы.Вставить("ИмяПользователяБазыСУБД", "user");
ПараметрыБазы.Вставить("ПарольПользователяБазыСУБД", "userpwd");
ПараметрыБазы.Вставить("БлокировкаРегламентныхЗаданийВключена", "on");

Попытка
	ИБ.Добавить(ИмяНовойБазы,,Истина,ПараметрыБазы);
Исключение
	ВызватьИсключение ОписаниеОшибки();
КонецПопытки;
```

**Comment by arkuznetsov** [comment]
Мог и упустить этот момент, посмотрю. Спасибо!

**Comment by leandr92** [comment]
Фикс финальный или еще подождать? Такой вариант я уже пробовал, и набор параметров перед вызовом команды вот такой (индекс №6). Он обрабатывается, но значение не присваивается.
```
ПараметрыКоманды
Массив
0:localhost:1545
1:infobase
2:--cluster=1b39c851-64d5-476e-afcc-b42badcc83fe
3:create
4:--name=test_taxi
5:--locale=ru_RU
6
7:--name=test_taxi
8:--dbms=PostgreSQL
9:--db-server=localhost
10:--db-name=test_taxi
11:--db-user=postgres
12:--db-pwd=1
13:--scheduled-jobs-deny=off
14:--license-distribution=allow
15:--date-offset=2000
```

**Comment by leandr92** [comment]
Добавил пулл реквест, который по идее должен исправить проблему.
https://github.com/arkuznetsov/irac/pull/43

**Comment by arkuznetsov** [comment]
@leandr92 Спасибо за PR, но проблема была глубже, сейчас должно работать.
