### ISSUE TITLE
При попытке запустить irac для ras, подключенному к другой машине, возникает ошибка:

### ISSUE THREAD

**Issue by m03mii** [arkuznetsov/irac#47]
Script started: 16.07.2020 14:30:00
ПРЕДУПРЕЖДЕНИЕ - Получен ненулевой код возврата -1: Ошибка соединения с сервером
Попытка установить соединение была безуспешной, т.к. от другого компьютера за требуемое время не получен нужный отклик, или было разорвано уже установленное соединение из-за неверного отклика уже подключенного компьютера

Script completed: 16.07.2020 14:30:21
Duration: 00:00:21.4732838

Должна ли библиотека irac работать по сети, когда сервер 1С расположен на другой машине?

**Comment by arkuznetsov** [comment]
У вас на сервере, к которому вы обращаетесь должна быть поднята служба RAS.
На машине, с которой вы вызываете методы irac должна быть установлена утилита RAC.
Проверьте, так ли это.

**Comment by m03mii** [comment]
Создал службу для пользователя 1С как в описании https://tavalik.ru/ustanovka-servera-administrirovanie-klastera-serverov-1spredpriyatiya/#p4, запустил. Попробовал снова подключиться через irac (rac установлена, той же версии), получил сначала еще ошибку при запуске rac.exe и такой лог:

ПРЕДУПРЕЖДЕНИЕ - Не удалось прочитать версию 1С "C:\Program Files\1cv8\8.3.14.1630\bin\rac.exe" -v .
{Модуль C:\Solutions\OneScript\lib\asserts\src\bdd-asserts.os / Ошибка в строке: 303 / [Failed] Ожидали, что проверяемое значение (-1073741819) БОЛЬШЕ ИЛИ РАВНО (0).
Ожидали, что код возврата <-1073741819> команды <"C:\Program Files\1cv8\8.3.14.1630\bin\rac.exe" -v > совпадет с ожидаемым <0>, а это не так!

Когда указал версию подробнее 8.3.14, ошибка прошла и сообщение как раньше.

**Comment by nixel2007** [comment]
а что выдает запуск "C:\Program Files\1cv8\8.3.14.1630\bin\rac.exe" -v
?

**Comment by m03mii** [comment]
Выдает такую же версию, 8.3.14.1630

**Comment by arkuznetsov** [comment]
а что выдает команда rac.exe <имя сервера где установлен RAS>:1545 cluster list?

**Comment by m03mii** [comment]
Выдает ошибку:
Ошибка соединения с сервером
Попытка установить соединение была безуспешной, т.к. от другого компьютера за требуемое время не получен нужный отклик,
или было разорвано уже установленное соединение из-за неверного отклика уже подключенного компьютера

**Comment by nixel2007** [comment]
а на сервере порт-то открыт?

**Comment by m03mii** [comment]
Большое спасибо! Заработала утилита irac. Был порт закрыт.
