### ISSUE TITLE
Ошибка при создании объекта УправлениеКластером1С

### ISSUE THREAD

**Issue by vsuh** [arkuznetsov/irac#50]
```
	АдминистрированиеКластера = Новый УправлениеКластером1С(Init.Конф[Префикс+"cluster"]
		 , 1545, , Init.Конф[Префикс+"clusterUser"], Init.Конф[Префикс+"clusterPasswd"]);
```

вызывает ошибку: 

> {Модуль C:\1c\Process\01_DumpIB\module.os / Ошибка в строке: 31 / Параметры конструктора: необходимых параметров: 0, передано параметров 5}

версия irac 1.0.0

Upd:
Если передавать конструктору меньше 4х параметров, то ошибка другая (в комментариях переданные параметры):

> C:\1c\Process>oscript 1.os   // "obr-app-13", 1545, "8.3.15.1700"
> {Модуль C:\Program Files\OneScript\lib\irac\src\Классы\ИсполнительКоманд.os / Ошибка в строке: 92 / Нельзя установить несуществующий путь к утилите RAC: C:\1c\Process\obr-app-13}
> 
> C:\1c\Process>oscript 1.os // "obr-app-13"
> {Модуль C:\Program Files\OneScript\lib\irac\src\Классы\ИсполнительКоманд.os / Ошибка в строке: 92 / Нельзя установить несуществующий путь к утилите RAC: C:\1c\Process\obr-app-13}
> 
> C:\1c\Process>oscript 1.os  // "localhost"
> {Модуль C:\Program Files\OneScript\lib\irac\src\Классы\ИсполнительКоманд.os / Ошибка в строке: 92 / Нельзя установить несуществующий путь к утилите RAC: C:\1c\Process\localhost}
>

**Comment by arkuznetsov** [comment]
Спасибо! Проверю.

**Comment by arkuznetsov** [comment]
Описание поправлю
