### ISSUE TITLE
Конструктор не найден (АдминистрированиеКластера)

### ISSUE THREAD

**Issue by vsuh** [arkuznetsov/irac#52]
```
#use irac

Админка = Новый АдминистрированиеКластера("obr-app-13", 1545, "8.3");

Кластеры = Админка.Кластеры();

```

> C:\1c\Process>oscript 1.os
> {Модуль C:\1c\Process\1.os / Ошибка в строке: 3 / Конструктор не найден (АдминистрированиеКластера)}
> 

пример из Readme.md не работает.

Upd:
пример из текущего Readme.md работает.
приведенный фрагмент скопирован из readme по ссылке из телеграм канала oscript, oscript-library, репозиторий [oscript-library/irac](https://github.com/oscript-library/irac)

**Comment by arkuznetsov** [comment]
Это устаревший синтакси, используйте Новый УправлениеКластером1С().
