### ISSUE TITLE
Не срабатывает заполнение параметра БлокировкаСеансовВключена 

### ISSUE THREAD

**Issue by denis-lopatkin** [arkuznetsov/irac#57]
При заполнении параметра не срабатывает ни на Истина, ни на Ложь
Код как из примера:

ПараметрыИБ = Новый Структура();
ПараметрыИБ.Вставить("НачалоБлокировкиСеансов", ДатаНачалаБлокировки);
ПараметрыИБ.Вставить("ОкончаниеБлокировкиСеансов", ДатаОкончанияБлокировки);
ПараметрыИБ.Вставить("СообщениеБлокировкиСеансов", СообщениеБлокировки);
ПараметрыИБ.Вставить("КодРазрешения", "654321");
ПараметрыИБ.Вставить("БлокировкаСеансовВключена", Истина);

ИБ.Изменить(ПараметрыИБ);

**Comment by arkuznetsov** [comment]
@denis-lopatkin Посмотри в пример, я там поправил, вместо "Истина" значение перечисления (ну или просто "on")/

**Comment by denis-lopatkin** [comment]
Да, сработало. Спасибо за подсказку, да и в целом за огромный труд!

**Comment by denis-lopatkin** [comment]
Артем добрый день! Столкнулся с другой проблемой\странностью - хочу
очистить параметры - не дает записать пустые значение.
Поля:
НачалоБлокировкиСеансов
ОкончаниеБлокировкиСеансов
СообщениеБлокировкиСеансов
КодРазрешения
Дату в разных форматах пробовал, текст пустой тоже не сохраняет. и код
блокировки не сбрасывает. Другой какой-то записывает, а пустую строку или
"" - нет.
Там какая-то специфическая функция для этого есть или что-то нет так, как
должно срабатывает?

ср, 1 сент. 2021 г. в 17:32, Artem Kuznetsov ***@***.***>:

**Comment by arkuznetsov** [comment]
@denis-lopatkin Надо поэкспериментировать с командной строкой RAC. Посмотрю на днях.

**Comment by denis-lopatkin** [comment]
Могу чем-то помочь? Я лицо заинтересованное :)

пт, 3 сент. 2021 г. в 14:45, Artem Kuznetsov ***@***.***>:

**Comment by arkuznetsov** [comment]
@denis-lopatkin Вот так отрабатывает из командной строки:
```
rac localhost:1545 infobase --cluster=9a7e1b89-3efb-4e81-a611-1f65e55a0da1 --cluster-user="admin" --cluster-pwd="admin" update --infobase=5c9a17fd-a5b9-46ba-9ebd-f24e94baa40b --denied-from="" --denied-to="" --denied-message="" --permission-code=""--sessions-deny=off
```
Проверь последнюю версию из develop.
