### ISSUE TITLE
Ошибка при выполнении команд с параметрами-флагами

### ISSUE THREAD

**Issue by alexmyt** [arkuznetsov/irac#58]
При выполнении команд с параметрами-флагами к параметру добавляются лишние символы "--".

Например, выполняем:
`Кластер.ИнформационныеБазы().Получить(ИмяИБ).Удалить("clear");`

Получаем:

> ОТЛАДКА - [oscript.lib.commands] - Полная строка запуска <"C:\Program Files\1Cv8\8.3.18.1289\bin\rac.exe"  ubuntu-interactive-1:1545 infobase --cluster=77fe4b8b-999a-437c-98e9-11b70a2475e5 drop --infobase=e14ccefa-887a-4ca4-bd7c-6ac60dca54c7 --infobase-user="Админ" --infobase-pwd="123" ----clear-database>
> 
> ПРЕДУПРЕЖДЕНИЕ - Получен ненулевой код возврата -1: Ошибка разбора параметра: ----clear-database

**Comment by arkuznetsov** [comment]
@alexmyt Спасибо! Проверь последний develop.

**Comment by alexmyt** [comment]
@arkuznetsov Спасибо, ошибка ушла.
