### ISSUE TITLE
авторизация управления кластером и на самих кластерах средствами os

### ISSUE THREAD

**Issue by Golovanoff** [arkuznetsov/irac#60]
В rac (для windows) у команды `admin register` есть возможность указать опцию `--auth=os` (или `--auth=pwd,os`), что позволяет авторизовываться на управлении кластерами и/или в кластерах средствами os.

Сейчас,  насколько я понял, в irac всегда ставится по умолчанию --auth pwd.

Хочется подключаться к кластерам без указания креденшиалов,  задав авторизацию средствами os.

**Comment by arkuznetsov** [comment]
Утилита rac не позволяет подключаться с использованием авторизации ОС. Указанный параметр только позволяет создать администратора сервера/кластера с авторизацией ОС. Т.е. создать можно, а использовать из rac нельзя. :-(
