### ISSUE TITLE
Идея: добавить в методы Список(...) возможность сортировки по одному из полей

### ISSUE THREAD

**Issue by 240596448** [arkuznetsov/irac#66]
Иногда хочется иметь отсортированный список (например, сеансов).
Хочется иметь возможность его сортировки по НомеруСеанса, имени пользователя, использованной памяти/процессора и т.п.

**Comment by arkuznetsov** [comment]
Я подумаю. Пока не хочется добавлять непосредственно в метод, т.к. либо будет неаккуратно, либо сломается совместимось.
Можно подсмотреть функцию сортировки тут: https://github.com/arkuznetsov/hirac/blob/497bdb30d682f246b1e6fb7aba9d0b989b6f5a9d/src/model/modules/%D0%9E%D0%B1%D1%89%D0%B5%D0%B3%D0%BE%D0%9D%D0%B0%D0%B7%D0%BD%D0%B0%D1%87%D0%B5%D0%BD%D0%B8%D1%8F.os#L473.

**Comment by nixel2007** [comment]
По флюент есть СортироватьПо

**Comment by 240596448** [comment]
> Я подумаю. Пока не хочется добавлять непосредственно в метод, т.к. либо будет неаккуратно, либо сломается совместимось.

Понял. 
Мне показалось, что параметр сортировки был бы красивее.
Разумеется, отдельно пересортировать можно как угодно.
